[workspace]
members = ["crates/*", "oracle-example"]
resolver = "2"

[workspace.package]
edition       = "2021"
version       = "0.1.0"
license       = "MIT"
repository    = "https://github.com/Lay3rLabs/example-avs-oracle"
rust-version  = "1.80.0"

[workspace.dependencies]
anyhow        = "1"
layer-wasi = { path = "crates/layer-wasi" }
slab = "0.4.9"
url = "2.5.2"
wasi = "=0.13.1"
wstd = "=0.4.0"
serde = { version = "1.0.210", features = [ "derive" ] }
serde_json = "1.0.128"
